# Generated by Django 6.0.1 on 2026-02-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_users', '0002_create_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_blog',
            name='penname',
            field=models.CharField(default='null', max_length=75),
        ),
    ]
